# Generated by Django 2.2 on 2020-11-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile-picture.png', null=True, upload_to=''),
        ),
    ]
